name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Events/Events.sln

    - name: Build
      run: dotnet build Events/Events.sln --no-restore

    - name: Test
      run: dotnet test Events/Events.sln --no-build --verbosity normal
